kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: server
spec:
  replicas: 1
  revisionHistoryLimit: 3

  template:
    metadata:
      labels:
        app: zipkin-test
        service: server

    spec:
      containers:
        - name: server
          image: "dr0l3/fts-server:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: "thrift"
              protocol: TCP

          env:
            - name: JAVA_OPTS
              value: "-Dcom.twitter.finagle.zipkin.initialSampleRate=1.0 -Dcom.twitter.finagle.zipkin.host=zipkin-service:9410 -server -Xmx512M -Xms512M -XX:MaxMetaspaceSize=128M -XX:+UseG1GC -XX:MaxGCPauseMillis=1000 -XX:InitiatingHeapOccupancyPercent=90 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"
