kind: Service
apiVersion: v1
metadata:
  name: service4
  namespace: test
spec:
  ports:
    - port: 8001
      targetPort: "thrift"
      protocol: TCP
      name: "thrift"

  selector:
    app: zipkin-test
    service: server4
