kind: Service
apiVersion: v1
metadata:
  name: service5
  namespace: test
spec:
  ports:
    - port: 8080
      targetPort: "http"
      protocol: TCP
      name: "http"

  selector:
    app: zipkin-test
    service: server5
